### ISSUE TITLE
Authentication issue with prometheus-to-sd

### ISSUE THREAD

**Issue by azymnis** [GoogleCloudPlatform/k8s-stackdriver#66]
Trying to use prometheus-to-sd in my project (as shown in the example kube config) but keep getting this error:

```
Error while sending request to Stackdriver googleapi: Error 403: Request had insufficient authentication scopes., forbidden
```

I also tried adding auth credentials for a service account that has the "monitoring admin" and "metrics writer" roles, but no dice. This is how the kube config for my prometheus-to-sd container looks like:

```
       - name: prometheus-to-sd
          image: gcr.io/google-containers/prometheus-to-sd:v0.2.1
          ports:
            - name: profiler
              containerPort: 6060
          command:
            - /monitor
            - --stackdriver-prefix=custom.googleapis.com
            - --source=kube-state-metrics:http://localhost:5000
            - --pod-id=$(POD_NAME)
            - --namespace-id=$(POD_NAMESPACE)
          volumeMounts:
            - name: prometheus-to-sd-cred
              mountPath: /etc/cred
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/cred/prometheus-to-sd-cred.json
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```

**Comment by crassirostris** [comment]
@azymnis Have you tried curl'ing `monitoring.googleapis.com` from inside the container? You can find example requests in the API Reference, e.g. [there](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/list).

**Comment by vially** [comment]
I'm also seeing this error very often in a kubernetes cluster deployed on GKE (kubernetes master version `v1.8.3-gke.0`).

This is the output of `kubectl describe deploy event-exporter-v0.1.7 --namespace=kube-system`:

```
Name:                   event-exporter-v0.1.7
Namespace:              kube-system
CreationTimestamp:      Tue, 17 Oct 2017 18:13:54 +0200
Labels:                 addonmanager.kubernetes.io/mode=Reconcile
                        k8s-app=event-exporter
                        kubernetes.io/cluster-service=true
                        version=v0.1.7
Annotations:            deployment.kubernetes.io/revision=2
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"event-...
Selector:               k8s-app=event-exporter,version=v0.1.7
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           k8s-app=event-exporter
                    version=v0.1.7
  Service Account:  event-exporter-sa
  Containers:
   event-exporter:
    Image:  gcr.io/google-containers/event-exporter:v0.1.7
    Port:   <none>
    Command:
      /event-exporter
    Environment:  <none>
    Mounts:       <none>
   prometheus-to-sd-exporter:
    Image:  gcr.io/google-containers/prometheus-to-sd:v0.2.2
    Port:   <none>
    Command:
      /monitor
      --stackdriver-prefix=container.googleapis.com/internal/addons
      --api-override=https://monitoring.googleapis.com/
      --source=event_exported:http://localhost:80?whitelisted=stackdriver_sink_received_entry_count,stackdriver_sink_request_count,stackdriver_sink_successfully_sent_entry_count
      --pod-id=$(POD_NAME)
      --namespace-id=$(POD_NAMESPACE)
    Environment:
      POD_NAME:        (v1:metadata.name)
      POD_NAMESPACE:   (v1:metadata.namespace)
    Mounts:           <none>
  Volumes:
   ssl-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   event-exporter-v0.1.7-7cb7c5d4bf (1/1 replicas created)
Events:          <none>
```

**Comment by x13n** [comment]
@vially Have you tried curl'ing as described above? Was there an error?

**Comment by vially** [comment]
@x13n It seems the affected cluster had Stackdriver Monitoring disabled. So `curl`ing from inside the container will most probably fail as well.

So I guess my actual problem is that this error spams the logs of clusters with `Stackdriver Monitoring` disabled.

I think it would be preferable to somehow silence it when monitoring is disabled. And does it even make sense to have this container running in clusters with monitoring disabled?

PS: This seems a completely different issue from the OP so I guess a new issue should be filled for it?

**Comment by x13n** [comment]
cc @loburm

**Comment by norbert-yoimo** [comment]
I'm running into the same problem as OP, but on GKE (1.9.3-gke.0). Could I get some pointers on how to start debugging this? I would try curling the URL @crassirostris mentioned, but I'm not sure what kind of credentials I'm supposed to use.

Interestingly, not all the logging attempts fail, only some of them.

Example of an error I'm getting:
```
{
 insertId:  "ibgtobg2fkvvpg"  
 labels: {
  compute.googleapis.com/resource_name:  "fluentd-gcp-v2.0.10-s2bg4"   
  container.googleapis.com/namespace_name:  "kube-system"   
  container.googleapis.com/pod_name:  "fluentd-gcp-v2.0.10-s2bg4"   
  container.googleapis.com/stream:  "stderr"   
 }
 logName:  "projects/myproject-157612/logs/prometheus-to-sd-exporter"  
 receiveTimestamp:  "2018-03-23T10:05:36.244542709Z"  
 resource: {
  labels: {
   cluster_name:  "myproject"    
   container_name:  "prometheus-to-sd-exporter"    
   instance_id:  "1284157316338905221"    
   namespace_id:  "kube-system"    
   pod_id:  "fluentd-gcp-v2.0.10-s2bg4"    
   project_id:  "myproject-157612"    
   zone:  "europe-west1-c"    
  }
  type:  "container"   
 }
 severity:  "ERROR"  
 textPayload:  "Error while sending request to Stackdriver googleapi: Error 403: Request had insufficient authentication scopes., forbidden"  
 timestamp:  "2018-03-23T10:05:33Z"  
}
```

**Comment by loburm** [comment]
@norbert-yoimo most probably it's related to the fact, that monitoring is disabled in your cluster (or in whole project). If you add monitoring scope to your nodes, it should fix the issue.

**Comment by norbert-yoimo** [comment]
Was there a change related to this recently? Logging was working fine for a long time, I just noticed problems popping up today.

**Comment by norbert-yoimo** [comment]
After granting the monitoring scope to the nodes, the errors disappeared, but I still don't see the logs in stackdriver.

**Comment by loburm** [comment]
Log line that you have shown is related to prometheus-to-sd component that is responsible for monitoring, not logging. 

What do you mean by failing fluentd? Is it restarted all the time, or you just see this warn messages? Maybe it worth to open separate bug in kubernetes repo.

**Comment by norbert-yoimo** [comment]
Sorry, I should have paid more attention when reading this issue. My problem was that I added a "severity" field in my logs, which was an int, and fluentd was failing when it was trying to upcase it as a string. I had to clear out the fluentd buffers from the nodes, and now it's logging again.

When I was looking for what the problem was, I assumed it to be related to this ticket, but it wasn't.

**Comment by yoheimuta** [comment]
I think that it is caused that GOOGLE_APPLICATION_CREDENTIALS is not loaded.

Since prometheus-to-sd refers to GCE's authority such as `Compute Engine default service account`, assigning roles / monitoring.metricWriter to GCE no longer causes errors.

As with custom-metrics-stackdriver-adapter #99, I think it would be better to modify it to use DefaultTokenSource instead of ComputeTokenSource, but what about that?

- https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/4034eb27d8506778f957aafe5ae2970ee84ac2e4/prometheus-to-sd/main.go#L91
- https://github.com/golang/oauth2/blob/cdc340f7c179dbbfa4afd43b7614e8fcadde4269/google/google.go#L149-L155
- https://github.com/golang/oauth2/blob/cdc340f7c179dbbfa4afd43b7614e8fcadde4269/google/default.go#L23

**Comment by davidxia** [comment]
Does this merged PR resolve this issue? https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/304

Does that PR support me using GOOGLE_APPLICATION_CREDENTIALS?
